[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = ["Eduard Dranca <eddranca@gmail.com.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "^1.34.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
